INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Fridge","Kitchen",3000,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Stove","Kitchen",2500,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Waste Bin","Kitchen",20,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Microwave","Kitchen",150,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Couch","Living Room",1500,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("TV","Living Room",800,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Fan","Living Room",200,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Entertainment Devices","Living Room",1200,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Use Items","Closet",500,"April 1, 2019","May 20, 2019");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("Snacks","Pantry",300,"April 1, 2019","May 20, 2019");


INSERT INTO users (name,age) VALUES ("Tom",22);
INSERT INTO users (name,age) VALUES ("Ben",23);
INSERT INTO users (name,age) VALUES ("Mary",20);
INSERT INTO users (name,age) VALUES ("Smith",23);
INSERT INTO users (name,age) VALUES ("June",21);
INSERT INTO users (name,age) VALUES ("Bill",22);
INSERT INTO users (name,age) VALUES ("Erin",23);
INSERT INTO users (name,age) VALUES ("Sara",21);
INSERT INTO users (name,age) VALUES ("Frank",20);
INSERT INTO users (name,age) VALUES ("Dan ",21);
INSERT INTO users (name,age) VALUES ("Benny",21);
INSERT INTO users (name,age) VALUES ("John",22);
INSERT INTO users (name,age) VALUES ("Felicia",20);
INSERT INTO users (name,age) VALUES ("Smithers",24);
INSERT INTO users (name,age) VALUES ("ManKirk",25);
INSERT INTO users (name,age) VALUES ("Tab",22);
INSERT INTO users (name,age) VALUES ("Spa",24);
INSERT INTO users (name,age) VALUES ("Aps",21);
INSERT INTO users (name,age) VALUES ("Greg",20);
INSERT INTO users (name,age) VALUES ("Bender",25);

INSERT INTO pledges (amount,user_id,project_id) VALUES (100,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,1,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,2,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,2,10);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,3,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,4,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,5,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,6,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,7,6);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,8,7);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,9,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,10,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,11,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,12,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,13,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,14,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,15,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,16,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,17,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,18,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,19,2);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,20,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,15,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,12,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,18,5);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,19,4);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,20,6);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,15,7);
INSERT INTO pledges (amount,user_id,project_id) VALUES (100,12,8);
